contour:
  envoy:
    service:
      type: ClusterIP
    hostPorts:
      enable: true

knative_serving:
  domain:
    type: real
    name: 127-0-0-1.sslip.io

kpack:
  kp_default_repository: https://index.docker.io/v1/
  kp_default_repository_username: [your username]
  kp_default_repository_password: [your password]

  registry:
    url: [REGISTRY_URL]
    username: [REGISTRY_USERNAME]
    password: [REGISTRY_PASSWORD]
  builder:
    # path to the container repository where kpack build artifacts are stored
    tag: [REGISTRY_TAG]
  # A comma-separated list of languages e.g. [java,nodejs] that will be supported for development
  # Allowed values are:
  # - java
  # - nodejs
  # - dotnet-core
  # - go
  # - ruby
  # - php
  languages: [java]
  image_prefix: [REGISTRY_PREFIX]

vendir:
  # For installation of CLI binaries
  host:
    # os: darwin, linux, windows
    os: "darwin"
    # arch: amd64, arm64
    arch: "amd64"
  # getLatest overrides declared versions (disable using getLatest: "")
  getLatest: ""
  versions:
    kn: 1.3.1
    kp: 0.4.2
    kubectl: 1.23.5
    tce: 0.11.0
    tce-apps-plugin: 0.6.0
    yq: 4.24.5
